### PR TITLE
Microservice dev: LLM & vector DB for video RAG 

### PR DESCRIPTION
**Pull request by shawnxhong**
## Description

4 functions separated out as independent microservices:
1. vector DB
2. model serve
3. video ingest
4. streamlit UI

## Issues

`n/a`.

## Type of change

- [ ] New feature (non-breaking change which adds new functionality)

## Tests

image

### CODE REVIEW

**Comment by shawnxhong** [comment]
Hi Tahani, I have updated the code using latest VisualRAGQnA code. Now 4 things are separated as microservices: vectorDB, model serve, video ingest and streamlit ui.

**Comment by ttrigui** [comment]
@shawnxhong Thank you so much. can you please check why the code scan fails https://github.com/ttrigui/GenAIExamples/actions/runs/9492836066/job/26213767831?pr=5?

**Comment by BaoHuiling** [comment]
> @shawnxhong Thank you so much. can you please check why the code scan fails https://github.com/ttrigui/GenAIExamples/actions/runs/9492836066/job/26213767831?pr=5?

Hello Tahani, please kindly notice I have removed the code which caused the security issue.

**Comment by BaoHuiling** [comment]
image
The tests has all passed, but I have to removed some unused file, let's wait for another round of check.

**Comment by BaoHuiling** [comment]
@ttrigui Hello Tahani, could you help to check the code scan workflow? I checked in some new features and triggered another test, but it says awaiting approval from a maintainer.
Besides, last example-test waits ~7 hours waiting for a runner to pick up, is that expected?
image

**Pull request closed without merging**
